import { NextRequest, NextResponse } from 'next/server'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { 
      transcriptionService, 
      transcriptionModel, 
      audioPath,
      s3Url 
    } = body
    
    // In a real application, you would call the actual transcription service
    // For now, we'll return mock data
    const mockTranscript = `This is a mock transcript generated by ${transcriptionService} using model ${transcriptionModel}. 
    
    The audio file was successfully transcribed from ${audioPath || s3Url}.
    
    This is just sample text to demonstrate the transcription functionality.
    In a real implementation, this would contain the actual transcribed content from the audio file.`
    
    const mockResponse = {
      transcript: mockTranscript,
      transcriptionModelUsed: transcriptionModel,
      transcriptionCostUsed: 0.05, // Mock cost in dollars
      duration: 930, // Mock duration in seconds
      wordCount: mockTranscript.split(' ').length
    }
    
    return NextResponse.json(mockResponse)
  } catch (error) {
    console.error('[API] Error running transcription:', error)
    return NextResponse.json(
      { error: 'Failed to run transcription' },
      { status: 500 }
    )
  }
}